#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TechnicalAnalyst.Droid.Resource", IsApplication=true)]

namespace TechnicalAnalyst.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int Loss_Red = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Profit_Green = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int table_Header = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int table_Text = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int btnCalc = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int btnReset = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int etClose = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int etHigh = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int etLow = 2131165190;
			
			// aapt resource value: 0x7f070012
			public const int lblbp1 = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int lblbp2 = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int lblbp3 = 2131165210;
			
			// aapt resource value: 0x7f070013
			public const int lblsl1 = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int lblsl2 = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int lblsl3 = 2131165211;
			
			// aapt resource value: 0x7f070000
			public const int tableLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int tableLayout2 = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int tableRow1 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int tableRow2 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int tableRow3 = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int tableRow4 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int tableRow5 = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int tableRow6 = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int tableRow7 = 2131165208;
			
			// aapt resource value: 0x7f070002
			public const int textView16 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int textView17 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int textView18 = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int textView28 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int textView33 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int textView34 = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int textView35 = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int textView39 = 2131165209;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
